//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shared
{ // 
    // This source code was auto-generated by xsd, Version=4.0.30319.1.
    // 


    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://my.ebXML.schema.com")]
    [System.Xml.Serialization.XmlRootAttribute("DoSomething", Namespace="http://my.ebXML.schema.com", IsNullable=false)]
    public partial class DoSomethingType {
    
        private PayloadType anObjectField;
    
        /// <remarks/>
        public PayloadType AnObject {
            get {
                return this.anObjectField;
            }
            set {
                this.anObjectField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://payload.company.com")]
    public partial class PayloadType {
    
        private string importantValueField;
    
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="integer")]
        public string ImportantValue {
            get {
                return this.importantValueField;
            }
            set {
                this.importantValueField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://payload.company.com")]
    public partial class ResponseType {
    
        private bool okField;
    
        /// <remarks/>
        public bool Ok {
            get {
                return this.okField;
            }
            set {
                this.okField = value;
            }
        }
    }

    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.1")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://my.ebXML.schema.com")]
    [System.Xml.Serialization.XmlRootAttribute("AcknowledgementResponse", Namespace="http://my.ebXML.schema.com", IsNullable=false)]
    public partial class AcknowledgementResponseType {
    
        private ResponseType responseObjectField;
    
        /// <remarks/>
        public ResponseType ResponseObject {
            get {
                return this.responseObjectField;
            }
            set {
                this.responseObjectField = value;
            }
        }
    }
}